### ISSUE TITLE
symlinks in tar files are not extracted to symlinks

### ISSUE THREAD

**Issue by martonilles** [onekey-sec/unblob#435]
7zip apparently just creates a file with the symlink target, which is inaccurate:
- https://sourceforge.net/p/sevenzip/bugs/1302/
- https://sourceforge.net/p/p7zip/bugs/137/
- https://sourceforge.net/p/sevenzip/bugs/1188/

**Comment by QKaiser** [comment]
Nothing happened in 10 years so better move to another extractor. `tar` should be sufficient I guess.

**Comment by vlaci** [comment]
The nix version is not affected, using `7-Zip [64] 17.04 : Copyright (c) 1999-2021 Igor Pavlov : 2017-08-28`

**Comment by vlaci** [comment]
We originally used tar, it got changed in 0dc17f8524017fcdc575e3a44f7980b9fb1a5f8c to protect from link traversal.

**Comment by QKaiser** [comment]
Enforcing a very specific version of 7-Zip is not workable.

We indeed replaced tar with 7z in https://github.com/onekey-sec/unblob/commit/0dc17f8524017fcdc575e3a44f7980b9fb1a5f8c. But since https://github.com/onekey-sec/unblob/pull/196, unblob takes care of canonicalizing symlinks.

That means we could use either `tar` or `unar`, choosing one or the other is a matter of opinion I guess.

**Comment by QKaiser** [comment]
Just opened a pull request that uses python's tarfile builtin module that we already use to calculate chunk offsets. I consider it to be a proper solution, especially when it comes to fighting parser differentials.
