### ISSUE TITLE
Optional "carving-only" Parameter

### ISSUE THREAD

**Issue by dorpvom** [onekey-sec/unblob#486]
Hi,

I was looking into integrating unblob in [FACT](https://github.com/fkie-cad/FACT_core) (more precisely [fact_extractor](https://github.com/fkie-cad/fact_extractor)) and needed unblob to work as a carver for this. Meaning, to ignore all the nice unpacker integrations you offer and maintain, and just extract the binary of e.g. file system, from the container blob.

I [implemented this](https://github.com/onekey-sec/unblob/compare/main...dorpvom:unblob:allow-carving-only) using a simple conditional triggered by a command line option.

So my question is: Is that interesting to you, i.e. should I make an effort to open a PR for this and possibly write test cases?

Cheers!

**Comment by QKaiser** [comment]
Hi ! Your proposal makes sense and limited in scope so I don't think we should refuse it.

We'll discuss it internally and I'll get back to you with more details. In the meantime you can open a merge request so that we can review it.

**Comment by martonilles** [comment]
@dorpvom I am just wondering what is the reason you do not need the extraction? In case a multi-layered blob you would need to call unblob recursively anyhow. Or you just do not need the extraction?

Otherwise thanks for the contribution and please go ahead an open a PR.
Quick glance on your branch:
- I would probably return early from the function when exraction skipped, probably doing `fix_extracted_directory`
- also this would imply using depth=1

**Comment by dorpvom** [comment]
Thanks for the feedback.

@martonilles The reason for skipping extraction for me specifically is that I want to use my own extraction harness for now and simply intend to replace good-old-binwalk. I do think it has some other use cases as well but that's it for me.

I'll look into the branch to incorporate your feedback and will then open a PR.
