### ISSUE TITLE
Latest docker is broken - "Unhandled exception during unblob"

### ISSUE THREAD

**Issue by ZeevR** [onekey-sec/unblob#959]
It seems the latest docker fails with the following error no matter what input it's given.

```
docker run --rm -v "$(pwd)":/data unblob /data/test.zip
{'exc_info': '0x1', 'event': 'Unhandled exception during unblob', 'level': 'error', 'timestamp': '2024-09-26 11:24.48', 'pid': 1}

```

**Comment by qkaiser** [comment]
It's a combination of different factors that led to this.

1. The last successful build of the unblob container happened when plottext version `5.3.1` completely disappeared from PyPi for unknown reasons. Meaning unblob is not actually installed within the container (the launcher is, but not the python module), since a dependency could not be installed.
2. In the meantime, our container security scanner policy blocked subsequent builds due to the presence of https://nvd.nist.gov/vuln/detail/CVE-2024-45490 within the Debian container.

Item 1 is fixed by https://github.com/onekey-sec/unblob/pull/958, container building will resume once https://github.com/onekey-sec/unblob/pull/960 is in.

In the meantime, I'd recommend you use the previous tagged version which is not affected by this issue:

```
docker run --rm -v "$(pwd)":/data unblob ghcr.io/onekey-sec/unblob:24.4.5 /data/test.zip
```

**Comment by qkaiser** [comment]
In the end your problem likely stemmed from the fact you were bind mounting to `/data` and not `/data/output`.

According to the documentation, this is how you should do it:

```sh
docker run --rm --pull always
-v "$(pwd)/output":/data/output \
-v "$(pwd)/input":/data/input \
unblob:latest /data/input/test.zip
```

This is because `/data/output` is unblob's workdir within the container.

Closing.

**Comment by kissgyorgy** [comment]
Hello @ZeevR!
We merged #960, but I think your command might also cause the error. 
[In the documentation](https://unblob.org/installation/#docker-image), you can find this example:
```
docker run \
  --rm \
  --pull always \
  -v /path/to/extract-dir/on/host:/data/output \
  -v /path/to/files/on/host:/data/input \
ghcr.io/onekey-sec/unblob:latest /data/input/path/to/file
```
which shows to bind mount to `/data/input` and `/data/output`.
This is because the default directory in the container is `/data/output`, so if you don't have an `output` directory on the host machine in the mounted directory, unblob will fail with a `Permission denied` error.
(We should do a better job to show that error in cases like this.)

I suggest to create an `output` directory in the directory you are mounting to `/data`.

**Comment by ZeevR** [comment]
Ok thanks, I'll test this tomorrow

**Comment by ZeevR** [comment]
:-/ The container still fails on any input (I tested 3 files).
Please don't force me to contribute an actual patch for this.

**Comment by qkaiser** [comment]
Can you copy/paste the exact command that you ran ?

**Comment by qkaiser** [comment]
This is what I'm seeing with the current container:

```
docker run --rm --pull always -it -v "$(pwd)":/tmp ghcr.io/onekey-sec/unblob:latest /tmp/xftp.zip
latest: Pulling from onekey-sec/unblob
Digest: sha256:3951303cb9cdb31e8837232b13288325c5c4db1fe08d8a12fee1da25e5f4badc
Status: Image is up to date for ghcr.io/onekey-sec/unblob:latest

╭──────────────────────────────────────────────────────────────────────────────────── unblob (24.6.10) ─────────────────────────────────────────────────────────────────────────────────────╮
│ Extracted files: 2                                                                                                                                                                        │
│ Extracted directories: 1                                                                                                                                                                  │
│ Extracted links: 0                                                                                                                                                                        │
│ Extraction directory size: 263.50 KB                                                                                                                                                      │
│ Chunks identification ratio: 100.00%                                                                                                                                                      │
╰───────────────────────────────────────────────────────────────────────────────────────── Summary ─────────────────────────────────────────────────────────────────────────────────────────╯
        Chunks distribution        
┏━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━┓
┃ Chunk type ┃   Size    ┃ Ratio  ┃
┡━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━┩
│ ELF64      │ 182.52 KB │ 69.27% │
│ ZIP        │ 80.97 KB  │ 30.73% │
│ UNKNOWN    │  0.00 B   │ 0.00%  │
└────────────┴───────────┴────────┘
```

**Comment by ZeevR** [comment]
`$ docker run --rm --pull always -it -v "$(pwd)":/tmp ghcr.io/onekey-sec/unblob:latest /tmp/input/test.zip
latest: Pulling from onekey-sec/unblob
Digest: sha256:3951303cb9cdb31e8837232b13288325c5c4db1fe08d8a12fee1da25e5f4badc
Status: Image is up to date for ghcr.io/onekey-sec/unblob:latest

╭───────────────────────────────────────────────────────────────────────── unblob (24.6.10) ──────────────────────────────────────────────────────────────────────────╮
│ Extracted files: 4                                                                                                                                                  │
│ Extracted directories: 1                                                                                                                                            │
│ Extracted links: 0                                                                                                                                                  │
│ Extraction directory size: 97.66 KB                                                                                                                                 │
│ Chunks identification ratio: 100.00%                                                                                                                                │
╰────────────────────────────────────────────────────────────────────────────── Summary ──────────────────────────────────────────────────────────────────────────────╯
        Chunks distribution        
┏━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━┓
┃ Chunk type ┃   Size   ┃  Ratio  ┃
┡━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━┩
│ ZIP        │ 41.39 KB │ 100.00% │
│ UNKNOWN    │  0.00 B  │  0.00%  │
└────────────┴──────────┴─────────┘


$ docker run --rm --pull always -it -v "$(pwd)":/data ghcr.io/onekey-sec/unblob:latest /data/input/test.zip
latest: Pulling from onekey-sec/unblob
Digest: sha256:3951303cb9cdb31e8837232b13288325c5c4db1fe08d8a12fee1da25e5f4badc
Status: Image is up to date for ghcr.io/onekey-sec/unblob:latest
{'exc_info': '0x1', 'event': 'Unhandled exception during unblob', 'level': 'error', 'timestamp': '2024-09-27 07:52.26', 'pid': 1}
`

It seems to not like /data at all for some reason.  I also tried with the command in the documentation and it didn't work.

**Comment by qkaiser** [comment]
As explained by @kissgyorgy and myself, since we're bind mounting to `/data` and that you're not creating specific bind mounts to `/data/input` and `/data/output` like in the documentation, you need to create those directories on the host otherwise you'll have permission issues.

If you really only want to bind mount `/data` to your current directory, then you need to do this:

```
mkdir input
mkdir output
mv test.zip input
docker run --rm --pull always -it -v "$(pwd)":/data ghcr.io/onekey-sec/unblob:latest /data/input/test.zip
```

**Comment by ZeevR** [comment]
Yes, after a bit more testing it seems docker on this box has some issues with sharing writeable folders in general with the containers. Not your fault. Sorry for the bother.
